import Sidebar from "@/components/Sidebar";
import "./globals.css";


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <div className="flex">
        <Sidebar/>
      <div className="flex-1 ml-14">  {children }</div>
     
        </div>
 
      </body>
    </html>
  );
}
