export const transactions = [
    {
      id: "TXN_001",
      userId: "aarav.patel",
      amount: 2450.0,
      location: "New York, NY",
      time: "2024-01-09 23:45:12",
      category: "Electronics",
      fraudScore: 85,
      status: "flagged",
      device: "iPhone 15 Pro",
      ipAddress: "192.168.1.100",
      paymentMethod: "Credit Card ****1234",
      merchant: "TechStore NYC",
      explanation:
        "Unusual late-night transaction with high amount from new device and location.",
      riskFactors: ["Late-night purchase", "High amount", "New device", "Location anomaly"],
    },
    {
      id: "TXN_002",
      userId: "meera.singh",
      amount: 89.99,
      location: "Los Angeles, CA",
      time: "2024-01-09 14:22:33",
      category: "Clothing",
      fraudScore: 25,
      status: "safe",
      device: "Samsung Galaxy S23",
      ipAddress: "10.0.0.45",
      paymentMethod: "Debit Card ****5678",
      merchant: "Fashion Outlet LA",
      explanation: "Normal shopping pattern at familiar merchant.",
      riskFactors: [],
    },
    {
      id: "TXN_003",
      userId: "krishna.verma",
      amount: 1200.0,
      location: "Miami, FL",
      time: "2024-01-09 16:15:44",
      category: "Travel",
      fraudScore: 65,
      status: "review",
      device: "MacBook Pro",
      ipAddress: "172.16.0.23",
      paymentMethod: "Credit Card ****9012",
      merchant: "SkyTravel Booking",
      explanation: "Large travel booking from unusual location.",
      riskFactors: ["High amount", "New location", "Travel category"],
    },
    {
      id: "TXN_004",
      userId: "fatima.shaikh",
      amount: 45.67,
      location: "Chicago, IL",
      time: "2024-01-09 12:30:15",
      category: "Food",
      fraudScore: 15,
      status: "safe",
      device: "iPhone 14",
      ipAddress: "192.168.0.55",
      paymentMethod: "Mobile Pay",
      merchant: "Downtown Deli",
      explanation: "Regular customer with consistent patterns.",
      riskFactors: [],
    },
    {
      id: "TXN_005",
      userId: "arjun.kumar",
      amount: 3200.0,
      location: "Las Vegas, NV",
      time: "2024-01-09 02:15:33",
      category: "Entertainment",
      fraudScore: 92,
      status: "blocked",
      device: "Unknown Device",
      ipAddress: "203.0.113.45",
      paymentMethod: "Credit Card ****3456",
      merchant: "Casino Royal",
      explanation: "Unrecognized device and high-risk category.",
      riskFactors: ["Very high amount", "Unusual time", "Unknown device", "Gambling"],
    },
    {
      id: "TXN_006",
      userId: "isha.roy",
      amount: 156.78,
      location: "Seattle, WA",
      time: "2024-01-09 10:45:22",
      category: "Groceries",
      fraudScore: 20,
      status: "safe",
      device: "Android Tablet",
      ipAddress: "10.1.1.88",
      paymentMethod: "Debit Card ****7890",
      merchant: "Fresh Market",
      explanation: "Typical groceries by known user.",
      riskFactors: [],
    },
    {
      id: "TXN_007",
      userId: "tanvi.rathore",
      amount: 999.0,
      location: "Austin, TX",
      time: "2024-01-09 20:30:00",
      category: "Home Decor",
      fraudScore: 72,
      status: "flagged",
      device: "MacBook Air",
      ipAddress: "172.18.1.12",
      paymentMethod: "Credit Card ****2222",
      merchant: "Urban Living",
      explanation: "First-time purchase in high amount category.",
      riskFactors: ["New category", "High spend", "Evening transaction"],
    },
    {
      id: "TXN_008",
      userId: "raj.menon",
      amount: 149.99,
      location: "Atlanta, GA",
      time: "2024-01-09 13:20:50",
      category: "Books",
      fraudScore: 18,
      status: "safe",
      device: "iPad Mini",
      ipAddress: "192.0.2.33",
      paymentMethod: "UPI",
      merchant: "PageTurners",
      explanation: "Consistent spending pattern.",
      riskFactors: [],
    },
    {
      id: "TXN_009",
      userId: "nikhil.banerjee",
      amount: 650.0,
      location: "Denver, CO",
      time: "2024-01-09 03:00:11",
      category: "Electronics",
      fraudScore: 78,
      status: "flagged",
      device: "Windows Laptop",
      ipAddress: "10.5.5.55",
      paymentMethod: "Credit Card ****3333",
      merchant: "GadgetZone",
      explanation: "High value purchase at night from infrequent shopper.",
      riskFactors: ["Night transaction", "High amount", "Low frequency"],
    },
    {
      id: "TXN_010",
      userId: "ananya.gupta",
      amount: 2200.0,
      location: "Phoenix, AZ",
      time: "2024-01-09 11:45:10",
      category: "Appliances",
      fraudScore: 68,
      status: "review",
      device: "Samsung Galaxy S20",
      ipAddress: "192.168.2.200",
      paymentMethod: "Credit Card ****8888",
      merchant: "ApplianceMart",
      explanation: "Medium risk — new merchant + large purchase.",
      riskFactors: ["New merchant", "High amount"],
    },
    {
      id: "TXN_011",
      userId: "rehan.chowdhury",
      amount: 59.0,
      location: "Boston, MA",
      time: "2024-01-09 09:10:35",
      category: "Utilities",
      fraudScore: 30,
      status: "safe",
      device: "iPhone 13",
      ipAddress: "192.168.1.77",
      paymentMethod: "NetBanking",
      merchant: "UtilityPay",
      explanation: "Regular monthly utility payment.",
      riskFactors: [],
    },
    {
      id: "TXN_012",
      userId: "neha.bhatt",
      amount: 3100.0,
      location: "San Francisco, CA",
      time: "2024-01-09 01:10:05",
      category: "Electronics",
      fraudScore: 95,
      status: "blocked",
      device: "Unknown Device",
      ipAddress: "198.51.100.100",
      paymentMethod: "Credit Card ****4444",
      merchant: "TechNation",
      explanation: "Blocked due to excessive amount from unknown source.",
      riskFactors: ["Very high amount", "New device", "Suspicious merchant"],
    },
    {
      id: "TXN_013",
      userId: "manav.joshi",
      amount: 870.0,
      location: "Houston, TX",
      time: "2024-01-09 18:15:20",
      category: "Furniture",
      fraudScore: 58,
      status: "review",
      device: "iPad Pro",
      ipAddress: "172.16.1.9",
      paymentMethod: "Credit Card ****5678",
      merchant: "FurniSpace",
      explanation: "First-time furniture purchase with medium risk.",
      riskFactors: ["New category", "Mid-high spend"],
    },
    {
      id: "TXN_014",
      userId: "shruti.nair",
      amount: 120.0,
      location: "Detroit, MI",
      time: "2024-01-09 07:50:42",
      category: "Health",
      fraudScore: 19,
      status: "safe",
      device: "Android Phone",
      ipAddress: "10.10.0.101",
      paymentMethod: "Debit Card ****7777",
      merchant: "HealthMart",
      explanation: "Routine medical product purchase.",
      riskFactors: [],
    },
    {
      id: "TXN_015",
      userId: "yash.malhotra",
      amount: 1850.0,
      location: "Orlando, FL",
      time: "2024-01-09 22:35:00",
      category: "Gaming",
      fraudScore: 84,
      status: "flagged",
      device: "Gaming PC",
      ipAddress: "10.10.10.10",
      paymentMethod: "Credit Card ****8888",
      merchant: "GameLand",
      explanation: "Flagged for large amount at night, high-risk digital item.",
      riskFactors: ["High amount", "Gaming category", "Night time"],
    },
    {
      id: "TXN_016",
      userId: "priya.chakraborty",
      amount: 240.0,
      location: "Charlotte, NC",
      time: "2024-01-09 17:42:17",
      category: "Beauty",
      fraudScore: 35,
      status: "safe",
      device: "iPhone 12",
      ipAddress: "192.168.3.33",
      paymentMethod: "UPI",
      merchant: "BeautyZone",
      explanation: "Normal beauty order by repeat customer.",
      riskFactors: [],
    },
    {
      id: "TXN_017",
      userId: "akash.seth",
      amount: 980.0,
      location: "San Diego, CA",
      time: "2024-01-09 05:30:12",
      category: "Appliances",
      fraudScore: 79,
      status: "flagged",
      device: "Windows Desktop",
      ipAddress: "172.20.0.10",
      paymentMethod: "Credit Card ****6565",
      merchant: "HomeTech Store",
      explanation: "Pre-dawn expensive appliance purchase by new user.",
      riskFactors: ["Early hours", "High spend", "First-time user"],
    },
    {
      id: "TXN_018",
      userId: "sana.qureshi",
      amount: 66.0,
      location: "Columbus, OH",
      time: "2024-01-09 11:25:33",
      category: "Food",
      fraudScore: 22,
      status: "safe",
      device: "iPhone 11",
      ipAddress: "192.168.1.91",
      paymentMethod: "UPI",
      merchant: "GreenBite",
      explanation: "Regular user placing lunch order.",
      riskFactors: [],
    },
    {
      id: "TXN_019",
      userId: "viraj.mehta",
      amount: 3900.0,
      location: "Brooklyn, NY",
      time: "2024-01-09 01:55:19",
      category: "Luxury",
      fraudScore: 97,
      status: "blocked",
      device: "Unknown Device",
      ipAddress: "203.0.113.199",
      paymentMethod: "Credit Card ****9898",
      merchant: "LuxeCart",
      explanation: "High-end purchase at suspicious time with unknown device.",
      riskFactors: ["Luxury category", "Midnight timing", "New device", "Very high amount"],
    },
    {
      id: "TXN_020",
      userId: "riya.singhania",
      amount: 110.5,
      location: "Portland, OR",
      time: "2024-01-09 08:10:40",
      category: "Stationery",
      fraudScore: 16,
      status: "safe",
      device: "MacBook",
      ipAddress: "192.168.2.88",
      paymentMethod: "Credit Card ****1111",
      merchant: "OfficeStack",
      explanation: "Low-risk purchase. Routine order pattern.",
      riskFactors: [],
    },
  ];
  
  export const stats = {
    totalFlagged: 47,
    blockedTransactions: 12,
    safeTransactions: 1834,
    avgFraudScore: 34.2,
    dailyTrend: [
      { date: "2024-01-03", flagged: 23, blocked: 5, safe: 1456 },
      { date: "2024-01-04", flagged: 31, blocked: 8, safe: 1623 },
      { date: "2024-01-05", flagged: 28, blocked: 6, safe: 1789 },
      { date: "2024-01-06", flagged: 42, blocked: 11, safe: 1567 },
      { date: "2024-01-07", flagged: 35, blocked: 7, safe: 1834 },
      { date: "2024-01-08", flagged: 39, blocked: 9, safe: 1723 },
      { date: "2024-01-09", flagged: 47, blocked: 12, safe: 1834 },
    ],
    categoryBreakdown: [
      { category: "Electronics", count: 15, percentage: 32 },
      { category: "Travel", count: 12, percentage: 26 },
      { category: "Entertainment", count: 8, percentage: 17 },
      { category: "Clothing", count: 7, percentage: 15 },
      { category: "Other", count: 5, percentage: 10 },
    ],
    locationBreakdown: [
      { location: "New York", count: 12, risk: "High" },
      { location: "Los Angeles", count: 8, risk: "Medium" },
      { location: "Chicago", count: 6, risk: "Low" },
      { location: "Miami", count: 9, risk: "Medium" },
      { location: "Las Vegas", count: 12, risk: "High" },
    ],
  }

  export const messages = [
    {
      id: 1,
      sender: "admin",
      message: "Why was user_132 flagged?",
      timestamp: "2024-01-09 15:30:00",
    },
    {
      id: 2,
      sender: "ai",
      message:
        "User_132 was flagged due to a combination of risk factors: The transaction occurred at 23:45 (unusual late-night activity), involved a high amount of $2,450 (significantly above their typical $200-500 range), was made from a new device (iPhone 15 Pro not previously associated with their account), and originated from a new location. The user's historical pattern shows daytime shopping with moderate amounts.",
      timestamp: "2024-01-09 15:30:05",
    },
    {
      id: 3,
      sender: "admin",
      message: "Any similar frauds detected today?",
      timestamp: "2024-01-09 15:32:00",
    },
    {
      id: 4,
      sender: "ai",
      message:
        "Yes, I've detected 3 similar patterns today: TXN_005 (user_078) was blocked for a $3,200 casino transaction at 2:15 AM from an unknown device. TXN_003 shows moderate risk with unusual location patterns. All involve late-night or early morning transactions with amounts significantly above user baselines. Would you like me to analyze the common factors?",
      timestamp: "2024-01-09 15:32:08",
    },
    {
      id: 5,
      sender: "admin",
      message: "Which region has the highest fraud risk?",
      timestamp: "2024-01-09 15:35:00",
    },
    {
      id: 6,
      sender: "ai",
      message:
        "Based on today's data, Las Vegas and New York show the highest fraud risk. Las Vegas has 12 flagged transactions with an average fraud score of 78%, primarily in entertainment and gambling categories. New York follows with 12 flagged transactions averaging 65% fraud score, mostly in electronics and high-value purchases. Both regions show unusual late-night activity patterns.",
      timestamp: "2024-01-09 15:35:12",
    },
  ]  